### ISSUE TITLE
Allow distinguishing between `?foo` and `?foo=`

### ISSUE THREAD

**Issue by xmo-odoo** [jplatte/serde_html_form#21]
Strictly speaking this is not actually part of `application/x-www-form-urlencoded` as the URL standard always requires a `=`, however more general URL handling / APIs can make the differentiation e.g.

- https://api.github.com/repos/jplatte/serde_html_form/git/trees/HEAD?recursive is not recursive
- https://api.github.com/repos/jplatte/serde_html_form/git/trees/HEAD?recursive= is recursive

This is almost certainly rooted in the ruby stdlib making the difference:
```ruby
irb(main):004:0> require "cgi"
=> true
irb(main):005:0> CGI.parse("foo")
=> {"foo"=>[]}
irb(main):006:0> CGI.parse("foo=")
=> {"foo"=>[""]}
irb(main):007:0> CGI.parse("foo=1")
=> {"foo"=>["1"]}
```

but currently it's not possible to get that information from SHF:
```rust
type R = std::collections::HashMap<String, serde_json::Value>;

fn main() {
    _ = dbg!(serde_html_form::from_str::<R>("foo"));
    _ = dbg!(serde_html_form::from_str::<R>("foo="));
}
```
```
[src/main.rs:4:9] serde_html_form::from_str::<R>("foo") = Ok(
    {
        "foo": String(""),
    },
)
[src/main.rs:5:9] serde_html_form::from_str::<R>("foo=") = Ok(
    {
        "foo": String(""),
    },
)
```

**Comment by robjtede** [comment]
I believe the current behavior to be correct according to specs that talk about it.

> If bytes contains a 0x3D (=), then ...
> 
> Otherwise, let name have the value of bytes and let value be the empty byte sequence.


https://url.spec.whatwg.org/#urlencoded-parsing

So, not `null`, but an empty byte sequence. Therefore:

- `?foo` is equivalent to `?foo=`
- `?foo=` deserializes to `("foo", "")`

**Comment by jplatte** [comment]
Right, given that I think it would be wrong to make these distinguishable after parsing.

Thanks for the great issue report though!
