### ISSUE TITLE
Bug consuming array structures in query string with `#[serde(flatten)]`

### ISSUE THREAD

**Issue by JuxhinDB** [jplatte/serde_html_form#6]
The following is a continuation of the discussion had here https://github.com/tokio-rs/axum/discussions/1719#discussioncomment-5194939. Code to reproduce this bug can be found [here](https://github.com/JuxhinDB/serde-html-form-bug/blob/main/src/main.rs#L37-L47).

---

There are situations where we need to parse one or more query string values into a single `Vec<T>`. For example using [`axum_extra`](https://docs.rs/axum-extra/latest/axum_extra/) `Query` handler.

```rust
#[derive(Debug, Deserialize)]
pub(crate) struct Params {
    #[serde(flatten)]
    pub(crate) parent: Filter,
}

#[derive(Debug, Deserialize)]
pub(crate) struct Filter {
    #[serde(default, rename = "filter")]
    pub(crate) children: Vec<String>,
}

async fn handler(params: Result<Query<BuggyParams>, QueryRejection>) -> String {
    let params = params.unwrap_or_default();
    println!("filters: {:?}", params);
    params.0.parent.children.join(",")
}
```

We expect the following behaviour:

* `?filter=1&filter=2` results in `params.0.parent.child` to be `["1", "2"]`, this works as intended;
* `?filter=1` results in `params.0.parent.child` to be `["1"]`, this fails as it parses the children as `String` rather than `Vec<String>`

This _only_ happens when combining this with `#[serde(flatten)]`. If the vector is at the top-level like so:

```rust
#[derive(Debug, Deserialize)]
pub(crate) struct Params {
    #[serde(default, rename = "filter")]
    pub(crate) filters: Vec<String>,
}
```

Then the parameters are parsed for `0..n` correctly.

**Comment by jplatte** [comment]
This is an instance of https://github.com/serde-rs/serde/issues/1183 and can't be fixed in thie library. I can only strongly recommend to not use `serde(flatten)` when you can help it. Even when it works, it degrades performance quite a lot compared to the equivalent solution without `flatten`.
